### ISSUE TITLE
Some random questions regarding `names.csv`

### ISSUE THREAD

**Issue by e9t** [everypolitician/everypolitician-data#1013]
Hi, thanks for the great work!
I was going through the data - specifically all `names.csv` - and found some peculiarities:

1. Bulgaria: [Some names](https://github.com/everypolitician/everypolitician-data/blob/master/data/Bulgaria/National_Assembly/names.csv#L2) are null, [some others](https://github.com/everypolitician/everypolitician-data/blob/master/data/Bulgaria/National_Assembly/names.csv#L43) have replicated terms (possibly last names) in the name column. Should this be fixed?
1. Ghana: [Most names](https://github.com/everypolitician/everypolitician-data/blob/master/data/Ghana/Parliament/names.csv#L15) are prepended with `Hon.` is this intentional, or should be fixed?
1. I see that [many people](https://github.com/everypolitician/everypolitician-data/blob/master/data/Moldova/Parlamentul/names.csv#L216) have aliases(i.e., multiple `name`s per `id`) in `names.csv`. However, you just have one `name` representing a person at [everypolitician.org](http://everypolitician.org/moldova/parlamentul/term-table/2014.html). How are you defining the representative form of a person? Are they chosen randomly or is there a specific rule? (IMO, I think explicitily having a canonical name for each entity would be useful in many usecases.)

(For the future) Is there a community where I can discuss and/or ask questions regarding this project, or can I just ask and discuss here?

**Comment by tmtmtmtm** [comment]
Hi @e9t,

Thanks for the interest. `names.csv` is still work-in-progress, with quite a few outstanding issues before we'd recommend that people use it for anything significant (which is a large part of why it's not documented anywhere yet). But on your specific questions:

1) Yes — they should definitely be fixed! The replicated names was due to a bug in the scraper, which I've now fixed (it'll take a little while to repopulate). The empty names are what's coming from the original source — e.g. http://www.parliament.bg/export.php/en/xml/MP/1015 — so it'll be a little more work to handle those. Will try to do so later today.

2) I actually noticed that one yesterday, but there's a slight complication in that the preferred fix would be in the scraper, but the official site that we're scraping has [vanished](http://www.parliament.gh/)! We could fix them all up manually, but I did some work yesterday on scraping the information from Wikipedia instead, so we can cross-match it and defer to those names instead (and also get better historic information too) — hopefully that should be finished in the next day or two. 

3) The rules around what ends up in the Popolo `name` field (which is what currently gets displayed on everypolitician.org, though we hope to change that soon to allow switching between representations in different languages) is quite ad hoc at the minute. This is complicated in several dimensions, as it's not only a language issue, but also that people very often don't _have_ one canonical name (whether over time, or at a single point in time). However, as you say, there are lots of times when consuming applications don't want to, and shouldn't need to, know anything about the (often country-specific) rules for which forms to use in which contexts — they just want a viable name to display (e.g. in [GenderBalance](http://www.gender-balance.org/)). At the minute we mostly default that to the most recent latin-script version of the name we have, but there are almost certainly exceptions to that. We're definitely open to suggestions for improvement here! Things are also complicated by plain JSON not really having strong conventions around how to handle i18n of strings. We may need to "upgrade" to JSON-LD solve this one well. 


Raising questions here is perfectly fine, or you can also email team@everypolitician.org.

**Comment by e9t** [comment]
Thanks for the quick reply! Will report if I find more "bugs"; and meanwhile close this issue for your convenience.

**Comment by tmtmtmtm** [comment]
Thanks — please do report any issues you see, and feel free to ask any questions about anything that's confusing or odd. We know that the documentation is generally quite far behind where we'd like it to be!
