### ISSUE TITLE
Update Cyprus last term name

### ISSUE THREAD

**Issue by wfdd** [everypolitician/everypolitician-data#10543]
It still says '2011–' [here](http://everypolitician.org/cyprus/) in the title though it's got the full end date below.  I'd fix it if I knew where to fix it.

**Comment by tmtmtmtm** [comment]
Good catch. I added the end date last week, but forgot to update the name. Fixed now (in the data; it'll flow through the site shortly).

**Comment by wfdd** [comment]
@tmtmtmtm

Thanks :)  Does it also need to be changed [here](https://github.com/tmtmtmtm/cyprus-openpatata/blob/master/scraper.rb#L77) or is the terms table redundant/being overwritten?

**Comment by tmtmtmtm** [comment]
No — that part of the scraper is redundant now. I switched to a manually maintained term file [last week](https://github.com/everypolitician/everypolitician-data/commit/f958de1e51d3438dbd689f088dc5711c2c9278f1), and haven't gotten around to removing it from the scraper yet (as it's not doing anything bad — just creating data that will be ignored; but if we're going to build it manually, may as well do it in EP itself, rather than the scraper)

**Comment by wfdd** [comment]
Thanks, that makes sense.
