### ISSUE TITLE
Ukraine: People incorrectly shown as independent

### ISSUE THREAD

**Issue by henare** [everypolitician/everypolitician-data#1468]
For example Гройсман Володимир Борисович is shown as independent when he's [actually](http://itd.rada.gov.ua/mps/info/page/17973) a member of _ПАРТІЯ "БЛОК ПЕТРА ПОРОШЕНКА"_.

The data only has this record for him:

```json
[
    {
        "id": "17973",
        "name": "Гройсман Володимир Борисович",
        "given_name": "Володимир",
        "patronymic_name": "Борисович",
        "family_name": "Гройсман",
        "area": "Загальнодержавному багатомандатному округу",
        "term": ​8,
        "start_date": "2014-11-27",
        "end_date": null,
        "image": "http://static.rada.gov.ua/dep_img8/bp4.jpg",
        "party": "ПАРТІЯ \"БЛОК ПЕТРА ПОРОШЕНКА\"",
        "source_url": "http://itd.rada.gov.ua/mps/info/page/17973",
        "faction": null,
        "faction_id": null
    }
]
```

So EveryPolitician should use the party field in this case.

**Comment by tmtmtmtm** [comment]
Hi @henare. This is because we assume that if the data is using factions, it should _always_ use factions, and parties are effectively irrelevant in that legislature. This in the behaviour that has best fit the reality that I've understood for pretty much every jurisdiction so far. 

https://en.wikipedia.org/wiki/Verkhovna_Rada#Composition implies that this is true in Ukraine also, and that the Rada only officially recognises factions, not parties. 

As Groysman is currently chairman of the Rada, I assume that — as in many countries — that means he has to be independent of any faction. If that's what's going on here, perhaps it might be more useful to set a pseudo-faction for that position instead?

**Comment by henare** [comment]
You're a :star2: Tony, thank you for explaining all of this.

I noticed it because he's shown as voting with his party a [couple](http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_golos?g_id=23) of [times](http://w1.c1.rada.gov.ua/pls/radan_gs09/ns_golos?g_id=24) at the start of the parliament.

From what you've said I think we're already doing the most pragmatic thing, so I'll close this for now.

**Comment by tmtmtmtm** [comment]
Oh, that's an interesting one. He's listed as being the Chairman since that date — do you know whether this means that these votes were _before_ that happening later the same day, or whether he chair at the time of those happening?

**Comment by tmtmtmtm** [comment]
Ah, just noticed the linked ticket. Yep — this is slightly tricky, but it doesn't seem too difficult:

* Adding separate membership records for the initial period as Independent until the Factions are formed/recognised (or, in this case, he becomes Speaker) is fairly straightforward — that's just like any other faction change. 

* Doing that at a _time_ rather than a date is a little trickier, as the EP workflow hasn't had to cope with that yet, but with suitable handwaving I don't think it should be _too_ tricky.

* If the source information doesn't have the time of the changes, it looks like it can be derived without too much difficulty from being different in consecutive votes. 

Even if the underlying voting app can't handle this level of detail yet, I think it would still be valuable to emit these changes somewhere so that the Membership records can become more correct (and thus available once you _do_ fix PublicWhip to be able to query on DateTime and not just Date)
