### ISSUE TITLE
Tonga

### ISSUE THREAD

**Issue by duncanparkes** [everypolitician/everypolitician-data#160]

**Comment by duncanparkes** [comment]
Scraper here: https://morph.io/duncanparkes/tonga

This doesn't currently include parties, as there is not data on them on the official site, and I couldn't immediately see it anywhere else. There is one noble listed without a constituency - this matches what's on the official site.

**Comment by tmtmtmtm** [comment]
Parties are rather important in a Tongan context, as this is only the second Parliament since the reforms under the new king, where they first became allowed, and there was lots of haggling over them (with the lead party offering ministry positions to independents if they would join up, so that they could form a majority and not have a Nobles-led government)

However, even more importantly, this data doesn't include an `id` column, so can't be processed at all. It also has mis-matching Term data (the records all say they're for the 2010 Term, but the `terms` table only lists the 2014 Term), and has quite a few invalid URLs in the `images` column too.

**Comment by duncanparkes** [comment]
Images now %quoted to get rid of spaces 79466eaf9358d84d776c05c9f0bc97b8b37e3fba

**Comment by duncanparkes** [comment]
Term for the records set to 2015 to match the terms table (I believe I chose 2015 rather than 2014 as the date the session started rather than the date of the election).
c37e537ebf6eab2aabfeb3e5992171dd4fe4790c

**Comment by duncanparkes** [comment]
Use final part of details_url as id:

https://github.com/duncanparkes/tonga/commit/0761df8749f14f2003df56c538247c5426e84dc4

**Comment by duncanparkes** [comment]
I still can't see who's in what party anywhere. It looks like parties are still basically unofficial.

**Comment by tmtmtmtm** [comment]
Closed by #229
