### ISSUE TITLE
Broken Import: Tuvalu

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#16430]
## Legislature

Tuvalu/Parliament

## Problem

"Person" called "Non-partisan" sneaking in — https://github.com/everypolitician/everypolitician-data/pull/16418

**Comment by octopusinvitro** [comment]
The scraper was fixed ([PR](https://github.com/everypolitician-scrapers/tuvalu-parliament-wikipedia/pull/1)) and is removing the 'non-partisans' properly if the scraper is run locally ([PR](https://github.com/everypolitician/everypolitician-data/pull/16563#commits-pushed-c10a83d)), but they are still coming in from morph because the database has not been deleted ([morph](https://morph.io/tmtmtmtm/tuvalu-parliament-wikipedia)). 

Also, the scraper needs to be moved to everypolitician-scrapers.

**Comment by octopusinvitro** [comment]
Closing as this was solved in https://github.com/everypolitician/everypolitician-data/pull/16661#commits-pushed-3f6e78c
