### ISSUE TITLE
Croatia -- Problem archiving pages

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#20617]
It appears that the scraper is not archiving correctly.

From the morph log:

_"The 'scraped_page_archive' gem wants to store the scraped pages in a git repo,but it cannot determine which git repo it should use.  See https://github.com/everypolitician/scraped_page_archive#usage for details of how to specify the repo."_

## Legislature

Croatia Parliament https://morph.io/tmtmtmtm/croatia-parliament

## Problem

The ENV variable needs to be set.

## Proposed Solution

Set the MORPH_SCRAPER_CACHE_GITHUB_REPO_URL variable.

**Comment by tmtmtmtm** [comment]
Looks like this is because the configuration was set on the https://morph.io/everypolitician-scrapers/croatia-parliament/ version instead.

The change that added this was https://github.com/everypolitician-scrapers/croatia-parliament/pull/2, which doesn't mention that the scraper was actually moved, or that the `instructions.json` file should be pointed at the new source.

I've added the configuration to the tmtmtmtm version, and disabled the everypolitician-scrapers one from running.
