### ISSUE TITLE
Malta Parliament -- scrape ex-members and end dates

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#24566]
# Source of New Data
~~~
'http://www.parlament.mt/brincat-leo'
'http://www.parlament.mt/joe-cassar'
'http://www.parlament.mt/fenech-albert'
~~~

## Legislature

Maltese Parliament

## Type of Data

Members.

## Notes

Some members have left the current term. Their URLs are still live but they are not listed on the members list page. Their pages will have to be hardcoded.

Electoral history dates are available for all members. It would be a good idea to capture the end dates of members who have left the current legislature.

**Comment by tmtmtmtm** [comment]
Rather than scrape these off the official site, I've added the relevant information to Wikidata, and scraped it from there instead: https://github.com/everypolitician-scrapers/maltese-parliament-wikidata

We should probably still scrape all the historic data from the Maltese Parliament site, but that's no longer in the critical path to getting the build working again.
