### ISSUE TITLE
Nigeria (House of Representatives) -- Old term incoming as new term

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#25459]
# Problem with Incoming Data

## Legislature
Nigeria (House of Representatives)

## Problem
Term 2015 is incoming as a new term though we already have that term in the current data.

**Comment by mhl** [comment]
> Term 2015 is incoming as a new term though we already have that term in the current data.

I might be missing something, but that's not how I read it.

> ### Added
> 
> *term/2015*
> 
> Ismaila Muazu Hassan

... is just one new person being found. The name changes are because we updated the scraper to get a fuller version of the name.

That said, on my list of things to do was to preserve the old (shorter form of the names) still in `other_names`, so I might as well make a PR with that now.

**Comment by mhl** [comment]
... and https://github.com/everypolitician/everypolitician-data/pull/25710 should be dealt with first anyway.

**Comment by tmtmtmtm** [comment]
I think this has been fixed by the combination of #25933 and #25935
