### ISSUE TITLE
Greenland (Inatsisartut): Changes in multiple terms

### ISSUE THREAD

**Issue by ondenman** [everypolitician/everypolitician-data#32799]
# Problem

Lots of changes in multiple terms. Deceased member is being added.

![pasted image at 2017_04_18 10_44 am](https://cloud.githubusercontent.com/assets/4107953/25125324/5d3a1a66-2426-11e7-88db-c85feffa7570.png)

Some members are losing email addresses:
![screen shot 2017-04-18 at 11 02 27](https://cloud.githubusercontent.com/assets/4107953/25125396/983b4eaa-2426-11e7-8914-f7cd339b53cb.png)

Scraper source is 404ing. http://en.inatsisartut.gl/members-of-inatsisartut.aspx

**Comment by ondenman** [comment]
The source url cited in the instructions file is not the same as the url (http://en.inatsisartut.gl/members-of-inatsisartut.aspx) that the scraper points to (http://www.ina.gl/inatsisartut/sammensaetning-af-inatsisartut/). The url in the scraper is working fine.

**Comment by tmtmtmtm** [comment]
* I've reconciled Bendt Frederiksen to the (previously incorrect) Bent Frederiksen (and similarly for Ussarqak vs Uusarqak Qujaukitsoq)
* I've switched the source URL in the instructions file to be simply the domain, rather than the members page (in keeping with most other sources)
* The other 'new' members for historic terms look to be legitimate — not sure if they simply weren't on the website before, or if there was a problem with the scraper
* None of the members losing email addresses seem to be current

Closed in https://github.com/everypolitician/everypolitician-data/pull/33766
