### ISSUE TITLE
Northern Cyprus

### ISSUE THREAD

**Issue by rubeenam** [everypolitician/everypolitician-data#478]
Official website of the Parliament: http://www.cm.gov.nc.tr/Default.aspx

Link to deputies: http://www.cm.gov.nc.tr/Milletvekillerimiz1.aspx

Provides basic info (party, constituency, birth date) plus resume of the Assembly members. Images not available for some members.

**Comment by tmtmtmtm** [comment]
Official site is nasty JS/ASP

Wikipedia: https://en.wikipedia.org/wiki/14th_Parliament_of_Northern_Cyprus

**Comment by wfdd** [comment]
@tmtmtmtm, I've now scraped all of them [here](https://morph.io/wfdd/nc-assembly-scraper).  The repo also contains the photos of all the current MPs, which need to/can be reconciled.

**Comment by tmtmtmtm** [comment]
Thanks @wfdd. Added in https://github.com/everypolitician/everypolitician-data/pull/11718

**Comment by wfdd** [comment]
@tmtmtmtm: Incidentally, I was surprised to see the current parliament is the 14th in Northern Cyprus.  I did a bit of digging and - well - it looks somebody on Wikipedia had simply [counted](https://en.wikipedia.org/w/index.php?title=14th_Parliament_of_Northern_Cyprus&diff=666356827&oldid=666347177) [up](https://en.wikipedia.org/w/index.php?title=14th_Parliament_of_Northern_Cyprus&diff=next&oldid=666356827) the elections since 1974, though two (in 1991 and 2006) were actually by-elections.  Also, the TRNC did not exist in name till 1983 and it doesn't look like they've got any numbering system in place anyway.  So, yaaa.

**Comment by wfdd** [comment]
It says [here](http://www.cm.gov.nc.tr/EskiFaaliyet.aspx) in the title of the latest ( annual report the current term is the eighth.

**Comment by tmtmtmtm** [comment]
Thanks @wfdd. Fixed.
