### ISSUE TITLE
Egypt

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#645]
http://parliament.gov.eg/

**Comment by h2g2bob** [comment]
http://parliament.gov.eg/MAP_SITE.aspx is the most promising page, but the link to "الاعضاء الحاليين" which google translates to "The present members" is `javascript:__doPostBack('ctl00$MainContent$LinkButton26','')` and does not work (links that work have a url in the second argument).

**Comment by h2g2bob** [comment]
It appears Egypt has no parliament right now (since 2012), according to http://www.aljazeera.com/news/2015/08/egypt-announces-elections-october-november-150830182012244.html

**Comment by tmtmtmtm** [comment]
Thanks @h2g2bob 

http://egpw.org/ has the full history of all Members from 1864-2012!

**Comment by tmtmtmtm** [comment]
http://www.parliament.gov.eg/members/ now includes the members elected from https://en.wikipedia.org/wiki/Egyptian_parliamentary_election,_2015

**Comment by struan** [comment]
There's a scraper at

https://morph.io/struan/egypt_parliament_members

which gather name, id and photo.

It's an ASP page so getting the rest of the details will involve working out what the relevant params are to generate in the form by inspecting the JavaScript links for each member. Doing that should make it possible to get a bit more information.

The IDs used are hidden one's associated with the images so I made the assumption that they are more likely to remain unique across terms rather than the ID displayed on the page.

**Comment by struan** [comment]
Scraper now updated to handle party, DOB and constituency.

**Comment by tmtmtmtm** [comment]
Closed by https://github.com/everypolitician/everypolitician-data/pull/6047
