### ISSUE TITLE
Jordan

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#655]
http://representatives.jo/english/Default.shtm?LanguageAction=English

**Comment by lizconlan** [comment]
Background info, condensed from http://representatives.jo/english/Fomation.shtm and  https://en.wikipedia.org/wiki/Politics_of_Jordan#Legislative_branch

Bicameral National Assembly (Majlis al-Umma).

**House of Representatives**" (Majlis al-Nuwaab) (also variously "Council of Representatives", "the House", the "Chamber of Deputies") - 150 Members, "elected through general, secret, and direct elections". Theoretical 4 year terms **but** the King may extend the term by 1-2 years or dissolve it early.

**Assembly of Senators** (Majlis al-Aayan) - 60 members appointed by the King for a four-year term

For future reference and to help screen out additional election lists, there is also an Executive Branch of government, comprising the King and his cabinet. Traditionally selected by the King, the cabinet has been chosen by election since 2011.

**Comment by confirmordeny** [comment]
http://www.senate.jo/en/content/members-current-council - members of Jordanian senate (current)
http://www.senate.jo/en/content/previous-councils - members of Jordanian senate (history)

**Comment by FOIMonkey** [comment]
Members of the house of representatives: http://representatives.jo/App/Public/Member/Viewa.asp?Company_ID=3066
and
http://representatives.jo/css-new/17.pdf

**Comment by tmtmtmtm** [comment]
Thanks @confirmordeny and @FOIMonkey.

The House of Representatives [apparently](https://en.wikipedia.org/wiki/Parliament_of_Jordan#Current_members_of_the_House_of_Representatives) has 6 members who are part of the Islamic Action Front. Don't suppose you've seen something to say which 6 those are?

**Comment by FOIMonkey** [comment]
That wiki page references the results of the 2007 election, when the last one was in 2013: https://en.wikipedia.org/wiki/Jordanian_parliamentary_election_results,_2013

**Comment by tmtmtmtm** [comment]
Ah, indeed. Are all current members Independents?

**Comment by FOIMonkey** [comment]
Yes, apart from those elected via the national list: https://en.wikipedia.org/wiki/Jordanian_parliamentary_election_results,_2013#National_List
