### ISSUE TITLE
Thailand

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#686]
http://www.parliament.go.th/

**Comment by davewhiteland** [comment]
http://politicalbase.in.th/index.php/Main_Page suggested (via ThaiNetizens)

**Comment by tmtmtmtm** [comment]
@davewhiteland is there a specific page on that with the list of members?

**Comment by davewhiteland** [comment]
Can't. Read. Thai :-(  (well I can read it phonetically which is, uh, useless here ;-) ). Will try to find out.

**Comment by davewhiteland** [comment]
Since May 2014 (2557 BE) the NCPO replaced the Senate and the House of Representatives in Thailand that had previously formed the Thai legislature to make the functional National Assembly.

via khun Pinda:

Here's the full lists of 220 NLC members: http://www.senate.go.th/w3c/senate/senator.php?id=18&page=1&orby=&orrg=ASC [includes images]

(Got it from www.senate.go.th. [Wikipedia Thailand also have the list](https://th.wikipedia.org/wiki/%E0%B8%AA%E0%B8%A0%E0%B8%B2%E0%B8%99%E0%B8%B4%E0%B8%95%E0%B8%B4%E0%B8%9A%E0%B8%B1%E0%B8%8D%E0%B8%8D%E0%B8%B1%E0%B8%95%E0%B8%B4%E0%B9%81%E0%B8%AB%E0%B9%88%E0%B8%87%E0%B8%8A%E0%B8%B2%E0%B8%95%E0%B8%B4_(%E0%B8%9B%E0%B8%A3%E0%B8%B0%E0%B9%80%E0%B8%97%E0%B8%A8%E0%B9%84%E0%B8%97%E0%B8%A2)_%E0%B8%9E.%E0%B8%A8._2557))

**Comment by davewhiteland** [comment]
Wikipedia list conveniently has the honorifics stripped from the names :+1:

**Comment by tmtmtmtm** [comment]
Yay; Now live at http://everypolitician.org/thailand/

Thanks @davewhiteland
