### ISSUE TITLE
Portugal

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/everypolitician-data#72]
Official: http://www.parlamento.pt/DeputadoGP/Paginas/Deputados.aspx

(Includes info on historic terms for current Deputies, but I can't find information on historic deputies)

Already scraped by http://demo.cratica.org/deputados/

**Comment by tmtmtmtm** [comment]
Scraped, and live.

**Comment by briatte** [comment]
My [scraper for Portugal](https://github.com/briatte/assembleia/blob/master/data.r) is a complete mess, because I could not find a proper way to work with ASP/doPostBack, but it shows that you can collect [quite a few variables](https://github.com/briatte/assembleia/blob/master/data.r#L281-L299) from the web pages.
