### ISSUE TITLE
Estonia: Start Date and End Date issues

### ISSUE THREAD

**Issue by marfi** [everypolitician/everypolitician-data#7492]
https://github.com/everypolitician/everypolitician-data/blob/master/data/Estonia/Riigikogu/term-12.csv#L8

This person appears to ends his tenure, before starting it. This could be a valid case, if the data refers to his previous term and then he was reelected. However if that is the case, this needs to be indicated better.

There are many more examples of this kind in this file:

https://github.com/everypolitician/everypolitician-data/blob/master/data/Estonia/Riigikogu/term-12.csv#L14

**Comment by tmtmtmtm** [comment]
Hi @marfi 

I'm not sure I'm following what the issue is here. 

The Andre Sepp record has a `start_date` of 2011-04-06 and an `end_date` of 2014-03-26, which seems OK to me.

Andres Jalak is listed with a `start_date` of 2011-12-06 and an `end_date` of 2014-03-26, which also seems fine.

Can you explain better what you think is wrong with these?

**Comment by marfi** [comment]
Hi @tmtmtmtm,

Impressed by the quick answer. I am a great fan of the project!

Ignore this issue. Obviously I got distracted. Of course there is no problem as the years are 2011 for the start. My bad.

Keep up with the good work!

M

**Comment by tmtmtmtm** [comment]
Hah, no worries. Glad it was just so simple :)

I'd love to hear more about what you're using the data for, or any requests for things we could do to improve it. Always useful to know what people are doing with it to help shape future priorities etc.

Feel free to just comment here if you're up for sharing more, or drop us a line at team@everypolitician.org
