### ISSUE TITLE
Finland: remove "vaalipiiri" from area

### ISSUE THREAD

**Issue by marfi** [everypolitician/everypolitician-data#7728]
In: https://github.com/everypolitician/everypolitician-data/blob/master/data/Estonia/Riigikogu/term-13.csv for example, the "area" column has the name of the Area and the word "vaalipiiri" (constituency) after it. This is not consistent with the rest of the data I've been going over so far: (UK, Estonia, Germany). I think it is save to have the word removed from the dataset at it is clearly that it is constituency.

**Comment by tmtmtmtm** [comment]
Good catch @marfi 

This field isn't really consistent across different countries — quite a few include modifiers like this (and sometimes it's not easy to just remove them as the place name is in a different declension in that form), but in this case it's more of a problem as it's inconsistent across the different terms. (We have to get the current data from a different source as http://kansanmuisti.fi/ still aren't up to date, due to the official source changing formats after the last election)

I've fixed that now, and it should hopefully all flow through in the next 10-15 mins.
