### ISSUE TITLE
Italy: Lowercase on first string in name & sort_name

### ISSUE THREAD

**Issue by marfi** [everypolitician/everypolitician-data#7890]
Both columns in the House and the Senate of Italy are listed in this format:

AIELLO Pietro

It will be nice if we can have them lowercased.

The issue might be related to #7741

**Comment by tmtmtmtm** [comment]
This is how the names are shown on the official site: http://www.camera.it/leg17/313

It's very difficult to know how to change the casing of names in a suitable manner programmatically (e.g. it would need to cope with names like "DALL'OSSO Matteo" here, and many other variations worldwide where people's names don't follow the pattern of starting with a single uppercase letter followed by all lowercase. 

In many cases the `other_names` section of the JSON representation will contain variations in the format you want, but there's unlikely to be a consistent way to get those in most cases. 

If you can find us a source that has all the relevant people for any legislature, we can always add that as a source, reconcile the people, expose extra fields from there, but otherwise we're largely at the mercy of what's either already in a given source, or that we can safely derive from it. And in this specific case I'm not confident enough that we'd get this right to justify trying to make this sort of transformation.

We probably _could_ safely take the parts that are in allcaps and use those to explicitly generate `family_name` and `given_name` columns that would flow through directly into the JSON (@andylolz, this is from your scraper — would you be interested in doing that, or adding @chrismytton and/or I as contributors so we can have a go?), which you could then convert at your end?

**Comment by tmtmtmtm** [comment]
Closing for now. Please reopen if this is significant issue, or if you can find a useful source with the data in this format.
